version: "3"

services:
  db:
    restart: always
    image: mysql:8.0

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "employees"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
volumes:db_data={}