version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inter
      MYSQL_ROOT_PASSWORD: "password!"
    volumes:
      - todo-mysql-data:/var/lib/mysql
