version: "3"

services:
  db:
    restart: always
    image: mysql:8.0

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "employees"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
  redis:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - appserver1
      - appserver2
  appserver1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - inter.env
    depends_on:
      - db
      - redis
  appserver2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - inter.env
    depends_on:
      - db
      - redis
  volumes:db_data={}
